"""empty message

Revision ID: a1596cf3229a
Revises: ffdc0a98111c
Create Date: 2023-03-23 09:02:01.770567

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'a1596cf3229a'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(
                        length=5000), nullable=False),
                    sa.Column('employees', sa.Integer(), nullable=False),
                    sa.Column('headquarters', sa.String(), nullable=False),
                    sa.Column('founded', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('ticker')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE stocks SET SCHEMA {SCHEMA};")

    op.create_table('portfolios',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('current_value', sa.Float(), nullable=False),
                    sa.Column('buying_power', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE portfolios SET SCHEMA {SCHEMA};")

    op.create_table('watchlists',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE watchlists SET SCHEMA {SCHEMA};")

    op.create_table('investments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('portfolio_id', sa.Integer(), nullable=False),
                    sa.Column('value', sa.Float(), nullable=False),
                    sa.Column('shares', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['portfolio_id'], ['portfolios.id'], ),
                    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE investments SET SCHEMA {SCHEMA};")

    op.create_table('portfolio_histories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('portfolio_id', sa.Integer(), nullable=False),
                    sa.Column('value_at_time', sa.Float(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['portfolio_id'], ['portfolios.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

    op.create_table('transactions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('portfolio_id', sa.Integer(), nullable=False),
                    sa.Column('total_cost', sa.Float(), nullable=False),
                    sa.Column('shares', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['portfolio_id'], ['portfolios.id'], ),
                    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE transactions SET SCHEMA {SCHEMA};")

    op.create_table('transfers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('portfolio_id', sa.Integer(), nullable=False),
                    sa.Column('deposit', sa.Float(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['portfolio_id'], ['portfolios.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE transfers SET SCHEMA {SCHEMA};")

    op.create_table('watchlist_stocks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('watchlist_id', sa.Integer(), nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
                    sa.ForeignKeyConstraint(
                        ['watchlist_id'], ['watchlists.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE watchlist_stocks SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_stocks')
    op.drop_table('transfers')
    op.drop_table('transactions')
    op.drop_table('portfolio_histories')
    op.drop_table('investments')
    op.drop_table('watchlists')
    op.drop_table('portfolios')
    op.drop_table('stocks')
    # ### end Alembic commands ###
